add:First Commit
conext-noc/ont_power_check pull request #1
Opened 2023-09-21 18:39 UTC by CesarSanch1998

2023-09-22 13:48 UTC, conext-noc requested changes
comentario general:
El codigo me parece bien en lineas generales, pero le faltan los cambios que te comente, no obstante, te recomiendo emplear la siguiente guia para nombramiento y nomenclaturas en python asi como tambien emplear todo el codigo en ingles.

guia: https://visualgit.readthedocs.io/en/latest/pages/naming_convention.html

2023-09-22 13:48 UTC, conext-noc commented on src/PT.py
> +def Unir():
Que hace esta funcion?, era una funcion de prueba?

2023-09-22 13:48 UTC, conext-noc commented on src/PT.py
> +    resultado = ssh('interface gpon 0/2\n display ont optical-info 4 all | no-more',4)
a pesar de estar bien, te recomiendo es enviar comando por comando porque la olt suele en alunas ocasiones no tomar bien este tipo de comandos seguidos.

2023-09-22 13:48 UTC, conext-noc commented on src/PT.py
> +    for line in lines[57:-3]:
que significa 57 y -3? son numeros magicos, trata de ponerlos en unas variables de manera que sepas de que trata.

2023-09-22 13:48 UTC, conext-noc commented on src/ssh.py
> +def ssh(comand,delay):
la funcion en lineas generales me parece bien, pero veo que cada vez que haces un comando haces una nueva session de ssh, trata de cambiar un poco la logica de manera tal que te mantengas sobre una misma session ssh.

2023-09-22 13:53 UTC, CesarSanch1998 commented on src/PT.py
> +def Unir():
tuve que eliminar varias cosas y esa función quedo sin utilizar mientras resolvía un problema

2023-09-22 13:54 UTC, ricardovera76 requested changes

2023-09-22 13:54 UTC, ricardovera76 commented on src/ssh.py
> +host = devices[f"OLT1"]["ip"]
Aqui siempre lo estas fijando para un equipo, como seria elcaso que lo hagas en simultaneo para 2 equipos?

2023-09-22 13:55 UTC, CesarSanch1998 commented on src/PT.py
> +    resultado = ssh('interface gpon 0/2\n display ont optical-info 4 all | no-more',4)
ssh('interface gpon 0/2\n ',1)
ssh('display ont optical-info 4 all | no-more',4)

algo así ? , los números después del comando hacen referencia a un tiempo de espera entre comando

2023-09-22 13:56 UTC, CesarSanch1998 commented on src/PT.py
> +    for line in lines[57:-3]:
Eso hace referencia después de que linea comenzar a tomar los datos y antes de que linea terminar.

2023-09-22 13:57 UTC, CesarSanch1998 commented on src/ssh.py
> +def ssh(comand,delay):
ok, tuve problemas al principio en reutilizar la misma sesión por eso fue esta implementación para ir adelantando mientras solventaba el problema.

2023-09-22 13:58 UTC, CesarSanch1998 commented on src/ssh.py
> +host = devices[f"OLT1"]["ip"]
Mi intención a largo es obtener los datos de la base de datos, así obtengo los fspo y los olt  para las consultas de las mismas.

2023-09-22 14:00 UTC, ricardovera76 commented on src/PT.py
> +def Unir():
Ok, trata de emplear para ese tipo de situaciones TDD (Desarrollo Impulsado por Pruebas en español) para que si tienes una idea de que o como debería de ser el resultado haz primero los tests y con los test que funcionen vas haciendo la función que necesitas al final.

2023-09-22 14:01 UTC, ricardovera76 commented on src/PT.py
> +    resultado = ssh('interface gpon 0/2\n display ont optical-info 4 all | no-more',4)
Si, así, haz el cambio y vuelve a hacer un push, automáticamente aparecerá el nuevo batch de cambios

2023-09-22 14:03 UTC, ricardovera76 commented on src/PT.py
> +    for line in lines[57:-3]:
Trata de ponerlos en unas variables fijas que sepas a que significan, porque si vuelves al proyecto mucho tiempo después no sabrás con exactitud a que te referías con esos 2 numeros

2023-09-25 17:52 UTC, ricardovera76 requested changes

2023-09-25 17:52 UTC, ricardovera76 commented on src/PT2.py
> +    print("Hola")
Esta funcion sigue sin tener ninguna relacion con el codigo mas alla de solamente imprimir un mensaje

2023-09-25 17:52 UTC, ricardovera76 commented on src/PT2.py
> +        if contador == 11:
que significa ese 11?

2023-09-25 17:52 UTC, ricardovera76 commented on src/PT2.py
> +            lista1.pop(0)
porque solo se elimina el primer elemento de la lista?

2023-10-02 15:00 UTC, conext-noc approved these changes
Se aprovara el MR, con la tentativa de los ultimos cambios mencionados, emplear nomenclatura de nombramiento, favor de seguir la siguiente guia oficial : https://visualgit.readthedocs.io/en/latest/pages/naming_convention.html

tambien con el cambio de nombres de variables a ingles para mejorar la documentacion del codigo.

2023-10-02 15:00 UTC, conext-noc commented on main.py
> +    bucle()
trata de cambiar los nombres a ingles.

2023-10-02 15:00 UTC, conext-noc commented on src/PT.py
> +from Constantes.config import *
los nombres de los modulos no deben de iniciar con mayusculas, solo las clases pueden usar PascalCase, UPPER_SNAKE_CASE para constantes y snake_case para funciones, modulos y variables, de igual manera trata de cambiar los nombres a ingles.

2023-10-02 15:00 UTC, conext-noc commented on src/PT.py
> +                        "contrato": "Error",#Esto se coloco porque me daba error ya que en ocaciones habia menos componentes en la lista en ve de 6 o mas tenia 5 porque en ocaciones
Entendible, trata de ser menos verbose con los comentarios para no llenar todo el archivo de ellos, solo pon commentarios en lugares clave con una muy muy breve descripcion.

2023-10-02 15:02 UTC, ricardovera76 approved these changes

2023-10-02 15:03 UTC, merged